name = "Half the Mods"
author = "Skye"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc38afcedf8ff158fe75b2055d1a94c971b38b32710de136667c93ed45cf1c28"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
